[project]
name = "google-cloud-run-jobs-template"
version = "0.0.1"
description = "Google Cloud Run template for uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = []
